4Science/DSpace

dspace/config/submission-forms.dtd
This is a cherry-pick of DSpace#1870 on top of your changes.
I hope it is ok, to create the pull request here? Because of the refactoring in this branch/pull request it would create merge conflicts if I would create a pull request directly on DSpace/DSpace:master.
=> DS-3724: Missing readonly in input-forms.dtd

dspace-api/src/main/java/org/dspace/submit/step/DescribeStep.java
fix for https://github.com/4Science/DSpace/issues/18
=> Mandatory type bind field issue

dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/AbstractBuilder.java, dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/BitstreamBuilder.java
This should fix the test failures in https://github.com/DSpace/DSpace/pull/1897
=> DS-3787: Cleanup deleted bitstreams after test

dspace-api/src/main/java/org/dspace/submit/step/StartSubmissionLookupStep.java, dspace-api/src/main/resources/Messages.properties, dspace-jspui/src/main/java/org/dspace/app/webui/json/SubmissionLookupJSONRequest.java, dspace-jspui/src/main/webapp/static/css/bootstrap/dspace-theme.css, dspace-jspui/src/main/webapp/static/js/submission-lookup.js, dspace-jspui/src/main/webapp/submit/start-lookup-submission.jsp
This PR allows to select multiple result from the start-submission-lookup step to import all of them in a single step
=> Multi import

dspace-api/src/main/java/org/dspace/statistics/content/StatisticsDataLogin.java, dspace-api/src/main/java/org/dspace/statistics/content/filter/StatisticsSolrGenericFilter.java, dspace-api/src/main/java/org/dspace/statistics/content/filter/StatisticsSolrLocationFilter.java, dspace-jspui/src/main/java/org/dspace/app/webui/servlet/LoginStatisticsServlet.java, dspace-jspui/src/main/java/org/dspace/app/webui/servlet/WorkflowStatisticsServlet.java
Fix the Travis build, hopefully
=> Add license headers

dspace-jspui/src/main/webapp/login-statistics.jsp, dspace-jspui/src/main/webapp/workflow-statistics.jsp
Function is misspelled and leads to an 'Internal Server Error'.
=> Fix typo in function name for login-statistic and workflow-statistic

dspace-api/src/main/java/org/dspace/submit/lookup/ScopusUtils.java
This PR improves Scopus import by using more appropriate author name fields when applicable.
=> fixes #57: improving Scopus author name import

dspace-jspui/src/main/java/org/dspace/app/webui/jsptag/ItemTag.java
Add <div class=\"table-responsive\"> to the Table listing the Bitstreams
=> Add "table-responsive" to Bitstream List

dspace-api/src/main/java/org/dspace/app/util/CollectionUtils.java
Rewrote `CollectionUtils.java` so that now it properly creates a ordered
CollectionsTree
=> [D4CRIS-844] Fixed collections ordering in New submission dropdown

dspace-api/src/main/java/org/dspace/authority/orcid/OrcidService.java
improve readability of code; fix associativity for boolean relator when inputtype:name is used on inputform
=> [D4CRIS-940][CST-2989]

dspace-api/src/main/java/org/dspace/identifier/doi/AssignDOIConsumer.java, dspace-api/src/main/java/org/dspace/submit/step/MintIdentifiersStep.java, dspace-api/src/main/java/org/dspace/submit/step/ShowIdentifiersStep.java, dspace-api/src/main/resources/Messages.properties, dspace-jspui/src/main/java/org/dspace/app/webui/submit/step/JSPShowIdentifiersStep.java, dspace-jspui/src/main/webapp/submit/list-identifiers.jsp, dspace-jspui/src/main/webapp/submit/review-identifiers.jsp, dspace/config/item-submission.xml
added the submission step to mint the identifiers
=> [D4CRIS-951] added the mint and show identifiers steps and added the assign DOI consumer

dspace-api/src/main/java/org/dspace/app/sherpa/SHERPAService.java, dspace-api/src/main/java/org/dspace/app/sherpa/submit/SHERPASubmitService.java, dspace-api/src/main/java/org/dspace/app/sherpa/v1/SHERPAJournal.java, dspace-api/src/main/java/org/dspace/app/sherpa/v1/SHERPAPublisher.java, dspace-api/src/main/java/org/dspace/app/sherpa/v1/SHERPAResponse.java, dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPAJournal.java, dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPAPermittedVersion.java, dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPAPublisher.java, dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPAPublisherPolicy.java, dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPAResponse.java, dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPASystemMetadata.java, dspace-api/src/main/resources/Messages.properties, dspace-jspui/src/main/java/org/dspace/app/webui/servlet/SHERPAPublisherPolicyServlet.java, dspace-jspui/src/main/webapp/sherpa/css/sherpa.css, dspace-jspui/src/main/webapp/sherpa/sherpa-policy.jsp, dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/UploadStep.java, dspace/config/dspace.cfg
This is a port of the SHERPA v2 API refactor, made to work with DSpace-CRIS 5.x
For details and testing instructions please see the DSpace 6.x version of this work at https://github.com/DSpace/DSpace/pull/2739
Developed by The Library Code with the support of Technische Universität Hamburg
=> SHERPA API v2 refactor for DSpace-CRIS 5.x

dspace-jspui/src/main/webapp/home.jsp
=> [D4CRIS-986] Switched places in homepage for side news and recent

dspace-api/src/main/java/org/dspace/app/mediafilter/MediaFilterCLITool.java, dspace-api/src/main/java/org/dspace/app/mediafilter/MediaFilterServiceImpl.java, dspace-api/src/main/java/org/dspace/app/mediafilter/service/MediaFilterService.java, dspace-api/src/main/java/org/dspace/ctask/general/MediaFilterCurationTask.java, dspace-jspui/src/main/webapp/tools/curate-item.jsp, dspace/config/dspace.cfg
and fixed MediaFilterCurationTask nullPointer because no filter classes were set
=> [D4CRIS-1009] Added configuration option to select which bundles the media filter must work

dspace-cris/jspui-webapp/src/main/webapp/dspace-cris/explore.jsp
Advanced Search Error bugs fix
=> [D4CRIS-1110]  Advanced Search Error bugs fix

dspace-cris/jspui-webapp/src/main/webapp/dspace-cris/explore.jsp, dspace-jspui/src/main/webapp/static/css/bootstrap/dspace-theme.css
css theme updated - layout bug fix
=> [D4CRIS-1068] css theme updated - layout bug fix

dspace-jspui/src/main/java/org/dspace/app/webui/servlet/BitstreamServlet.java
the tmp file was deleted while the corresponding InputStream was still in use
=> [CST-5212] fix InputStream used after tmp file is deleted

dspace-cris/jspui-api/src/main/java/org/dspace/app/webui/cris/controller/json/EPersonController.java, dspace-cris/jspui-api/src/main/java/org/dspace/app/webui/cris/servlet/AuthorityClaimServlet.java
and fix EPersonController sending uuid to rp edit instead of string
=> [D4CRIS-1134] fix authority claim servlet using current user crisid instead of selected rp

dspace-api/src/main/resources/Messages.properties, dspace-jspui/src/main/java/org/dspace/app/webui/util/EditItemUtil.java, dspace-jspui/src/main/webapp/layout/header-submission.jsp, dspace-jspui/src/main/webapp/static/js/edit-item-display-tables.js, dspace-jspui/src/main/webapp/tools/edit-item-form.jsp, dspace/config/dspace.cfg
Improvements in Edit Admin mode.
New Edit mode implemented.
Changes in bundle way of displaying
=> [D4CRIS-1145] Improvements in Edit Admin mode for big bundles

dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java, dspace/config/modules/oai.cfg
=> [D4CRIS-1151] fix in OAI indexing & removed item.cerifentitytype usages

dspace-jspui/src/main/java/org/dspace/app/webui/util/ThumbDisplayStrategy.java
Generate a default thumbnail for item without a thumbnail
=> [AV-20] Showing default thumbnail if thumbnail is not present/generated

dspace-jspui/src/main/java/org/dspace/app/webui/jsptag/ItemTag.java, dspace-jspui/src/main/java/org/dspace/app/webui/util/ThumbDisplayStrategy.java, dspace-jspui/src/main/webapp/static/css/bootstrap/dspace-theme.css
Display default thumbnail in item page for each bitstream
=> [AV-20] Added default thumbnail in item page

dspace-api/src/main/java/org/dspace/discovery/FullTextContentStreams.java, dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java, dspace/config/modules/discovery.cfg
=> [D4CRIS-1157] fix - adding tika to index fulltext

dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java, dspace/config/modules/discovery.cfg
Porting tika improvements on dspace cris 6
=> [D4CRIS-1157] Adding tika client improvement to extract fulltext

dspace/config/spring/api/discovery.xml
* Fixes #[issue-number] https://github.com/4Science/DSpace/issues/305 #305 
Missing Discovery Index for communities and collections.
- Note: The regarding search configuration `communityOrCollection` is set in the `ScopeSelectorModalComponent` https://github.com/4Science/dspace-angular/blob/dspace-cris-7/src/app/shared/search-form/scope-selector-modal/scope-selector-modal.component.ts .
- new discovery index with collections and communities
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 
After configuration of this discovery index the search scope selector should not be empty.
_This checklist provides a reminder of what we are going to look for when …
=> communityOrCollection discovery configuration

dspace/etc/migration/do_migration.ktr, dspace/etc/migration/entity_migration.ktr
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Related to [REST Contract](https://github.com/DSpace/Rest7Contract)
Improves the migration of DO / research objects.
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.
* change filter condition of entities migrated during this do migration jobs turn to some regex. In our case we had some
`awards` and `awardseries` entities, the last one beginning with the same prefix, which were wrongly processed/recognized by the existing LIKE condition. As a result the `awardseries` entities were also imported into the `awards` collection, but with no data at all.
* The …
=> Improve migration of DO's

dspace/etc/migration/dspace_cris_migration.kjb
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Related to [REST Contract](https://github.com/DSpace/Rest7Contract)
Migrating former 5.10 Orgunits with nested objects is currently not possible.
This PR references the correct table names.
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.
* change reference to database table names for property (prop) and property definition (pdef)
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 
_This checklist provides a reminder of what we …
=> fix table name in orgunits nested object migration

dspace/etc/migration/entity_migration.ktr
_Add references/links to any related issues or PRs. These may include:_
* Fixes #[issue-number]
* Related to [REST Contract](https://github.com/DSpace/Rest7Contract)
Migrate cris properties (pointing/referencing) to epersons 
- f.e. editusers properties being used for cris object policydefinition
- this PR does not migrate groups. properties pointing to groups are currently not migrated :)
- added multiple steps to migrate eperson references (partly shown on the screenshot below)
- cris properties with old_jdyna_values.dtype == 'eperson' are resolved to the belonging eperson. The email is added as the metadata_value and the uuid as the metadata_authority.
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, …
=> migrate eperson references

dspace/config/crosswalks/oai/service-description.xml
* Fixes https://github.com/4Science/DSpace/issues/392
use dspace7 configuration parameters instead of legacy dspace5 config.
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.
* change WebsiteURL (assume the is meant to be the frontend url)  
* use server.url (starting with https://) as the OAIPMHBaseURL
**Include guidance for how to test or review your PR.** This may include: steps to reproduce a bug, screenshots or description of a new feature, or reasons behind specific changes. 
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are …
=> use common config parameters for oai openairecris service description
