dspace-api/src/main/java/org/dspace/submit/lookup/ScopusService.java
dspace-cris/api/src/main/java/org/dspace/app/cris/batch/ScopusFeed.java
dspace/config/spring/api/bte.xml

outputMap’s key “dc.identifier.eid” should be equal to
scopusOutputGenerator’s property “sourceIdMetadata”. Changed the
outputMap’s value from “dc.identifier.eid” to “dc.identifier.scopus”.

Fix mapping for scopus id

---

dspace-api/src/main/java/org/dspace/submit/lookup/ScopusService.java
dspace-cris/api/src/main/java/org/dspace/app/cris/batch/ScopusFeed.java

At the top of the loop we check for the existence of the eid value in
the record and skip the record if it doesn’t exist.

Fix crash for nonexisting scopus id

---

dspace-cris/jspui-api/src/main/java/org/dspace/app/webui/cris/util/ItemCrisRefDisplayStrategy.java

rp can be a null pointer; if so, rp.getMetadata will throw an
exception and the code below is never reached. This happens for
deleted profiles.
(This is my first PR, it's just a tiny change. Please let me know if I'm doing something wrong.)
It might be better not to show an icon for deleted profiles at all, but this change avoids a null pointer exception and a logged message whenever that happens.

null pointer fix in ItemCrisRefDisplayStrategy.java

---

dspace-jspui/src/main/webapp/layout/header-submission.jsp
dspace-jspui/src/main/webapp/static/js/custom-functions.js

The basic design of the administrative panel of DSpace CRIS might increase unintentional deletion of CRIS/JDynA items (RPs, OrgUnits, Boxes, Tabs, etc.), since there's no confirmation and buttons are inappropriate arranged. There's merely a gap between editing or deleting an existing box/tab.
This pull request adds a simple yet effective confirmation dialog in front of every* button/link, which deletes an item.
The confirmation applies to every button/link with `[id^=delete]` (CRIS entities) or `.jdynaremovebutton` (JDynA entities).
*as far as I could identify

Add confirmation before deleting CRIS/JDynA items

---

dspace-cris/api/src/main/java/org/dspace/app/cris/batch/ImportCRISDataModelConfiguration.java

On import, this small typo causes the `new-line` option to be always set to `false` for nested objects.
Compare line `894` and `897`, which contradict each other.

Fix flawed 'equals' check when importing cris-configuration.xls

---

dspace-jspui/src/main/java/org/dspace/app/webui/util/AbbreviateTextDisplayStrategy.java
dspace-jspui/src/main/webapp/display-item.jsp
dspace-jspui/src/main/webapp/static/js/abbreviatetext.js
dspace-jspui/src/main/webapp/submit/edit-metadata.jsp
dspace-jspui/src/main/webapp/submit/review-metadata.jsp
dspace/config/dspace.cfg

This pull requests addresses DSpace's issue with `textareas`, not allowing the user to insert a line break in a suitable way.
By default DSpace disables the 'ENTER' key to prevent "accidentally submitting a form when the 'Enter' key is pressed".
Running text, e.g. abstracts or descriptions, can only be inserted as continuous text, without sensible structure through paragraphs.
*This pull request does not require additional dependencies.*
This pull request restricts the 'disabled ENTER key' functionality to `inputs` other than `textarea`.
Furthermore, running text may clutter the item view, hence abbreviating text, which exceeds a specific length, is reasonable.
This pull request also addresses an issue with running text being rendered as one continuous block of text in the submission's …

Enable ENTER key in textareas and add suitable rendering of running text (e.g. abstracts, etc.)

---

dspace-cris/api/src/main/java/org/dspace/app/cris/importexport/ExcelBulkChange.java

Fix issue #14 
> The workaround is to insert a control char (e.g. #) in the last empties columns to control the empty cell in the row (this works as delimiter char).
The correction described is no longer necessary but the code continues to work even with files with the control character (#).

D4CRIS-25 XLS import thrown ArrayIndexOutOfBoundsException

---

dspace-cris/api/src/main/java/org/dspace/app/cris/integration/RPMultiAuthority.java

With the latest changes, our migration processes were not able to assign author RPs properly to our publications. The flaw lies in the newly introduced `RPMultiAuthority` we are using.
When using `RPMultiAuthority` as choices plugin, every functionality which relies on `getBestMatches()` to get a list of possible matching RPs, will fail to assign the RPs properly, because the possible matches are ... never returned.
This PR fixes this issue, what seems like a careless mistake.

Fix issue in RPMultiAuthority.java which prevents migration processes to properly find best matching RPs for given name

---

dspace-cris/api/src/main/java/org/dspace/app/cris/batch/ScriptCrisUnsubscribeEPerson.java
dspace-cris/api/src/main/java/org/dspace/app/cris/util/UnsubscribeEPersionUtils.java
dspace/config/emails/unsubscriptions

A new script was created to unsubscribe an ePerson from all notifications: all communities, collections, Cris objects and statistics. After execution, the command sent an email to the alert.recipient or registration.notify email address.
The command is executed using the email as parameter:
`dspace dsrun org.dspace.app.cris.batch.ScriptCrisUnsubscribeEPerson -e email`

4CRIS-810 Script to unsubscribe an eperson from all the notification

---

pom.xml

As stated on https://jira.duraspace.org/browse/DS-3733, there is a problem with Xalan 2.7.1 when supplementary Unicode characters   are in the metadata of an item, causing the break of OAI webapp.
The solution is to revert to Xalan 2.7..0

Supplementary unicode characters breaking OAI

---

dspace-jspui/src/main/java/org/dspace/app/webui/jsptag/ItemTag.java
dspace-jspui/src/main/webapp/display-item.jsp

Added the `<div class="col-lg-9">` that was closed in `ItemTag.render()` but
was never opened and resulted in improper formatting,
Added `col-lg-9` to the `<div>` in `ItemTag.renderFull()` to match
`ItemTag.render()`,
Extended the space occupied by the `<div class="row">` that
contains the table and the boxes from 9 to 12 columns.

[D4CRIS-848] The side boxes in the full item view now properly display on the side

---

dspace-jspui/src/main/java/org/dspace/app/webui/util/Authenticate.java

Error in Authenticate.java class caused by anothet porting of commit of DSpace. This cause an NPE 
on all PostLoggedInAction.

[D4CRIS-899]Erroneous block code brackets

---

dspace-jspui/src/main/java/org/dspace/app/webui/jsptag/DiscoveryArtifactTag.java

This allows that thumbnails are shown in discovery item lists (used in most viewed, most cited, recently added components), provided `<property name="thumbnail" value="true" />` is set in `dspace/config/spring/api/global-list-layout.xml` and that `webui.preview.enabled = true` in `dspace/config/dspace.cfg`

Show basic thumbnail if branded_preview bundle missing

---

dspace/config/crosswalks/mapConverter-orcid-worktype.properties

For ORCID API version 3 a new type mapping for theses is required: https://info.orcid.org/documentation/integration-and-api-faq/#easy-faq-2682.
Thus this PR changes that mapping.

changes worktype mapping for Thesis to match ORCID API 3 requirements

---

dspace-cris/api/src/main/java/org/dspace/app/cris/sitemap/CrisObjectsSitemapGenerator.java

In our sitemap the paths to projects are incorrect (there is a "pj" in the path instead of "project", cf https://tore.tuhh.de/sitemap?map=0). I believe I have found the problem in the code and have prepared a fix for that with this PR.

fixes path problem for projects in sitemap

---

dspace-api/src/main/java/org/dspace/discovery/IndexClient.java
dspace-api/src/main/java/org/dspace/discovery/IndexingService.java
dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
dspace-cris/api/src/main/java/org/dspace/app/cris/discovery/CrisSearchService.java

Checks whether DB contains items not indexed by Solr. 
Running the script allows to check and restore not indexed items 
Script execution:
./dspace index-discovery -d

[D4CRIS-1119] Indexing add option to compare DB vs SOLR

---

dspace/etc/migration/entity_migration.ktr

DSpace 7.3 added the metadata schema change `REPLACE cris.owner with dspace.object.owner` in the Flyway script `V7.3_2022.09.28__Orcid_refactoring.sql`.
This change was not considered in the CRIS entity migration transformation (`entity_migration.ktr`). This leads to error messages (`ERROR: Metadata field: 'cris.owner.null' was not found in the registry.`) when running the CRIS entity migration process on DS-CRIS 2022.03.
- create a RP in a DS-CRIS 5.11 instance - make sure that the corresponding row in `cris_rpage` has a resolvable eperson ID in column `epersonid`
- apply migration to DS-CRIS 2022.03 as described in the DS-CRIS 2022.03 documentation
- run `ItemImportMainOA` via DS CLI
- the migration of the RP leads to the error message: `ERROR: Metadata field: 'cris.owner.null' was not …

use metadata field dspace.object.owner instead of cris.owner in CRIS entity migration

---

dspace/etc/migration/publications_migration.ktr

`publications_migration.ktr` contains a hard-coded path to `migration_configuration.xls`.

remove hard-coded path to migration_configuration.xls

---

dspace/config/crosswalks/DIM2DataCite.xsl

This PR adds ORCID for authors to the DataCite DOI registration crosswalk. The ORCID is taken from the virtual author-orcid field in DSpace-CRIS passing the ORCID iD from the person to the publication.

adds ORCID to DataCite crosswalk

---

dspace/config/crosswalks/mapConverter-scopusToCoarPublicationTypes.properties
dspace/config/spring/api/crosswalks.xml
dspace/config/spring/api/scopus-integration.xml

This PR introduces type mapping for Scopus. The types coming in the scopus response are being mapped to DSpace-CRIS compliant COAR types.
No specific instructions, it's a simple configuration change.

introduces type mapping to COAR types for Scopus

---

dspace/config/emails/subscriptions_content

* Related to #318 
* Addition to https://github.com/4Science/DSpace/commit/38c254a5f9ab3316ee077b346da0fe226f05b32f
* Related to https://github.com/DSpace/DSpace/pull/8772
While https://github.com/4Science/DSpace/commit/38c254a5f9ab3316ee077b346da0fe226f05b32f fixes the application of the subject to any email, there is still the subject parameter missing for subscription emails.
This PR adds a subject to the subscription email of contents.
It's just a minor PR for a configuration file, so I guess there are no instructions for reviewers needed.

adds subject to subscription emails

---

dspace/etc/migration/relations_migrations.ktr

* Fixes https://github.com/4Science/DSpace/issues/329
Proper relationship entries after migration.
- both fields are already in the stream which is processed by the last step of pentahos relations_migration.ktr.
- to test: apply this specific migration step without this fields
- check table relationship;
- truncate table relationship;
- apply migration with this fields
- check table relationship;
- Add leftward_type into column leftward_value
- Add rightward_type into column rightward_type
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to …

migration fix missing relationship values

---

dspace/config/submission-forms.xml

The current version of `submission-forms.xml` is not schema valid (with respect to `submission-forms.dtd`). 
The order of elements within `field` is in conflict with the element order given in the schema definition:
```
dc-schema, dc-element, dc-qualifier?, language?, repeatable?, label, style?, type-bind?, input-type, hint, required?, regex?, vocabulary?, visibility?, readonly?
```
Due to the large amount of errors in `submission-forms.xml` it is hard to determine "real schema conflicts" in the file editor / IDE.

resolve XML schema violations in submission-forms.xml

---

dspace-api/src/main/java/org/dspace/subscriptions/SubscriptionEmailNotificationServiceImpl.java

* Fixes #380
This PR resets information about modified or added items in subscription context. (see #380)
See #380 for more information about the bug, which is resolved here.
* This PR just adds clearing of the item cache for subscriptions

Reset information about modified or added items in subscription context

---

dspace-api/src/main/java/org/dspace/orcid/model/factory/impl/OrcidAffiliationFactory.java
dspace-api/src/main/java/org/dspace/orcid/model/factory/impl/OrcidSimpleValueObjectFactory.java
dspace/config/spring/api/orcid-services.xml

…adata security level/visibility before calculating the metadata signature for orcid profile objects
* Fixes https://github.com/4Science/DSpace/issues/393 #`394` (if this fixes an issue ticket)
Short summary of changes (1-2 sentences).
configurable option to exclude non-public metadata based on their metadata security level/visibility before calculating the metadata signature for orcid profile objects.
Please add a more detailed description of the changes made by your PR. At a minimum, providing a bulleted list of changes in your PR is helpful to reviewers.
* introduced configurable option which returns true when the metadata security level is null or 0 . The parameter is some boolean which can be added to the ObjectFactory generating the orcid Profile Section …

orcid profiles exclude non-public metadata 

---

dspace-api/src/main/java/org/dspace/app/ldn/dao/LDNMessageDao.java
dspace-api/src/main/java/org/dspace/app/ldn/service/impl/LDNMessageServiceImpl.java
dspace-api/src/main/java/org/dspace/discovery/indexobject/LDNMessageEntityIndexFactoryImpl.java
dspace-server-webapp/src/main/java/org/dspace/app/rest/LDNMessageRestController.java
dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/LDNMessageEntityConverter.java
dspace-server-webapp/src/main/java/org/dspace/app/rest/model/LDNMessageEntityRest.java
dspace-server-webapp/src/test/java/org/dspace/app/rest/LDNMessageRestControllerIT.java

+ move LDN Messages enqueueretry endpoint to a POST 
+ javadocs 
+ item casting/conversions 
Frontend part at: https://github.com/4Science/dspace-angular/pull/78

move enqueueretry to POST
